version: "3.9"
services:
  apichamp:
    image: apichamp/apichamp-core:1.3.4
    ports:
      - "8080:8080"
    volumes:
      - ./specs:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: database_pets
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: samplepwd
    user: postgres
    volumes:
      # Be aware that for sample purposes the data is not mounted and therefore not consistent.
      #- ./db/storage:/var/lib/postgresql/data:rw
      - ./db/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s