specification: 1.0

operations:
  'get /pets':
    fulfillments:
      - name: pets
        type: read
        datasource: postdb
        queries:
          - if: param.limit != null
            query: SELECT * FROM pets_sample.pets LIMIT :[param.limit]
          - query: SELECT * FROM pets_sample.pets
        exceptions:
          - if: param.limit != null && param.limit > 100
            statuscode: 412
            message: The limit must not be bigger then 100

    mappings:
      'Pet':
        id: pets.id
        name: pets.name
        species: pets.type

  'post /pets':
    fulfillments:
      - name: createPet
        type: update
        datasource: postdb
        queries:
          - query: INSERT INTO pets_sample.pets (name, color) VALUES (:[body.name], :[body.species])

      - name: pets
        type: read
        datasource: postdb
        queries:
          - query: SELECT * FROM pets_sample.pets WHERE id = :[createPet.id]

    mappings:
      'Pet':
        id: pets.id
        name: pets.name
        species: pets.species

  'get /pets/{petId}':
    fulfillments:
      - name: pets
        type: read
        datasource: postdb
        queries:
          - query: SELECT * FROM pets_sample.pets WHERE id = :[param.petId]

    mappings:
      'Pet':
        id: pets.id
        name: pets.name
        species: pets.type

datasources:
  postdb:
    type: db
    url: jdbc:postgresql://database_pets:5432/postgres
    user: postgres
    password: samplepwd

authentications:
  basicauth:
    type: basicauth
    user: demo
    password: demo

authentications:
  basicauth:
    type: basicauth
    user: demo
    password: demo

settings:
  debug: true