specification: 1.0

operations:

  'get /products':
    fulfillments:
      - name: product
        type: READ
        datasource: demodb
        instructions:
          - if: PARAM(category) != NULL()
            query: SELECT id, name, details, category, price, stock FROM product WHERE category = :[PARAM(category)]
          - query: SELECT id, name, details, category, price, stock FROM product

    responses:
      - name: success
        statuscode: 200
        default: true
        schema:
          list: VALUE(product, $)
          item:
            productid: VALUE(@, $.id)
            title: VALUE(@, $.name)
            description: VALUE(@, $.details)
            category: VALUE(@, $.category)
            price: VALUE(@, $.price)
            stock: VALUE(@, $.stock)

datasources:

  demodb:
    type: db
    url: jdbc:mariadb://database_products:3306/sample-products
    user: root
    password: samplepwd

settings:
  debug: true