version: "3.9"
services:
  apichap:
    image: apichap/apichap-core:latest
    ports:
      - "8080:8080"
    volumes:
      - ./specs:/app
    depends_on:
      postgres-pets:
        condition: service_healthy

  postgres-pets:
    image: postgres:latest
    container_name: postgres-pets
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: samplepwd
    user: postgres
    volumes:
      # Be aware that for sample purposes the data is not mounted and therefore not consistent.
      - ./db/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s